### ISSUE TITLE
Feature Request: Use RP Fence as base model

### ISSUE THREAD

**Issue by Jack-Chronicle** [Chrisdw889/StylishStiles#7]
I use a Resource Pack to make Fences look better, and would love for the Stiles to match the aesthetic. Wondering if it's at all possible to create a method for it to use the textures from the Fences?

**Comment by Chrisdw889** [comment]
Thanks for the feature request. I will look into this. Which Resource Pack are you interested in?

**Comment by Jack-Chronicle** [comment]
I'm hoping to get the Vanilla Tweaks "fencier fences" textures to be compatible with it

**Comment by Chrisdw889** [comment]
Unfortunately I have been unable to find a way to generate the textures on runtime based on which resource packs are activated. However, I will look into making a resource pack add-on for Vanilla Tweaks.

**Comment by Chrisdw889** [comment]
I have created a resource pack for use alongside fencier fences. It can be found here: https://modrinth.com/resourcepack/stylish-stiles-fencier-fences
